<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\Icons\bebb7fbb3f23d2157e1ecc8224686535.ico</ApplicationIcon>
    <WindowsSdkPackageVersion>10.0.19041.38</WindowsSdkPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests\**" />
    <None Remove="tests\**" />
    <EmbeddedResource Remove="tests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0" />
    <PackageReference Include="System.Management" Version="9.0.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\bebb7fbb3f23d2157e1ecc8224686535.ico" />
    <Resource Include="Resources\QRCodes\7f09a53bd669d32db250c8ead9e924d4.jpg" />
    <Resource Include="Resources\QRCodes\24aeaa7d3f01dd052ae11d91cd29eac1.jpg" />
    <Resource Include="Resources\QRCodes\gzh.jpeg" />
    <Resource Include="Resources\Donate\596dd377-5795-4576-94f0-0d0865384f8c.png" />
  </ItemGroup>

</Project>
